[package]
name = "server"
version = "0.1.0"
authors = ["py-162157 <765007043@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.2.0", features = ["full"] }
rand = "0.8.3"